<?php

/**
 * Plugin Name: W2A by Sourov
 */



function my_rest_prepare_post( $data ) {
    $_data = $data->data;

    $imageUrl = get_term_meta($_data['id'] ,'_fm', true);
    if ($imageUrl=="") {
        $imageUrl = "https://picsum.photos/400/300";
    }
    $_data['featured_image_url'] =   $imageUrl ;
    $data->data = $_data;
    return $data;
}
add_filter( 'rest_prepare_category', 'my_rest_prepare_post', 10, 3 );


function increase_per_page_max($params){
    $params['per_page']["maximum"] = 1000;
    return $params;
}

add_filter('rest_comment_collection_params', 'increase_per_page_max');


function filter_rest_allow_anonymous_comments()
{
    if (isset($_POST['let_me_insert'])) {
        return true;
    }
    return false;
}

add_filter('rest_allow_anonymous_comments', 'filter_rest_allow_anonymous_comments');


add_action ( 'category_edit_form_fields', function( $tag ){
    $cat_fm = get_term_meta( $tag->term_id, '_fm', true ); ?>
    <tr class='form-field'>
        <th scope='row'><label for='cat_fm'><?php _e('Category Feature Image'); ?></label></th>
        <td>
            <input type='text' name='cat_fm' id='cat_fm' value='<?php echo $cat_fm ?>'>
            <p class='description'><?php _e('Image for the Category '); ?></p>
        </td>
    </tr> <?php
});
add_action ( 'edited_category', function( $term_id ) {
    if ( isset( $_POST['cat_fm'] ) ){
        update_term_meta( $term_id , '_fm', $_POST['cat_fm'] );
    }
       
});



add_filter('rest_prepare_post', 'my_filter_post', 10, 3);
function my_filter_post($data, $post, $context)
{


    // Does this have categories?
    if (!empty($data->data['categories'])) {
        $first = true;
        // Loop through them all
        foreach ($data->data['categories'] as $category_id) {
            // Get the actual Category Object
            if ($first) {
                $category = get_category($category_id);

                $data->data['w2a_by_sourov']["catName"] = $category->name;
            }
            $first = false;
        }
    }
    if (!empty($data->data['featured_media'])) {
        $image_full =  wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'full');
        $image_thumbnail =  wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'thumbnail');
        if ($image_full!=null) {
            $data->data['w2a_by_sourov']['image_full'] =$image_full[0];
        }
        if ($image_thumbnail!=null) {
            $data->data['w2a_by_sourov']['image_thumbnail'] =$image_thumbnail[0];
        }
    }

    return $data;
}



function make_notification_option($actions, $page_object)
{
    $actions['google_link'] = '<a href="' .menu_page_url('w2a-setting', false).
'&type=post'.
'&postid='. urlencode($page_object->ID).
'&firebase=view'.
 '" class="google_link">' . __('Send notification') . '</a>';

    return $actions;
}

add_filter('post_row_actions', 'make_notification_option', 10, 2);





/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class WASetting {
	private $w2a_setting_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'w2a_setting_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'w2a_setting_page_init' ) );
	}

	public function w2a_setting_add_plugin_page() {
		add_menu_page(
			'W2A setting', // page_title
			'W2A setting', // menu_title
			'manage_options', // capability
			'w2a-setting', // menu_slug
			array( $this, 'w2a_setting_create_admin_page' ), // function
			'dashicons-admin-settings', // icon_url
			2 // position
		);
	}

	public function w2a_setting_create_admin_page() {
		$this->w2a_setting_options = get_option( 'w2a_setting_option_name' ); 
        
              
        if (isset($_GET['firebase']) && $_GET['firebase']=="view" && isset($_GET['postid'])) {
            $post =get_post($_GET['postid']);
    
   ?>

<div class="wrap">
    <h2>W2A Settings</h2>
    <p>W2A by Sourov settings page</p>
    <?php settings_errors();
    
            wp_enqueue_style('tableCss', plugin_dir_url(__FILE__) . '/inc/css/table.css', array(), '1.1', 'all');
            
            $w2a_settings_options = get_option('w2a_settings_option_name'); 
            
            if (isset($_GET['response'])) {
                $response = urldecode( $_GET['response']);
             echo'  <div class="notice notice-success is-dismissible hide" id="notificationFormNotice">
             <p>'. $response.'</p>
         </div>';
            }

            $w2a_setting_options = get_option( 'w2a_setting_option_name' ); // Array of All Options
           $server_id_0 = $w2a_setting_options['server_id_0']; // server id
           $package_name_1 = $w2a_setting_options['package_name_1']; // package name
            ?>

   
    <div class="section-form">
        <form method="get" action="">
            <div class="intro">
                <h1>Ready to send notification?</h1>
                <h2>Modify or just click "Send"</h2>
            </div>
            <label>Notification Title</label>
            <input type="text" name="title" value="<?php echo $post->post_title ; ?>" required>
            <label>Notification Body</label>
            <input type="text" name="body" value="<?php echo $post->post_title ; ?>" required>
            <label>Post ID</label>
            <input type="text" name="id" value="<?php echo $post->ID ; ?>" required>
            <label>Post URL</label>
            <input type="text" name="selfUrl" value="<?php echo get_permalink($post->ID) ; ?>" required>
            <label>Notification Image Link</label>
            <input type="text" name="imageLink"
                value="<?php echo wp_get_attachment_url(get_post_thumbnail_id($post->ID), 'thumbnail') ; ?>">
            <label>Notification Topic</label>
            <input type="text" name="topic" value="<?php echo $package_name_1; ?>" required>
            <input type="hidden" name="page" value="w2a-settings">
            <input type="hidden" name="firebase" value="send">
            <input type="submit" value="Send" />
        </form>
    </div>

</div>
     
     <?php


        }else{

        
  
        ?>

		<div class="wrap">
			<h2>W2A setting</h2>
			<p>Config this website for app</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'w2a_setting_option_group' );
					do_settings_sections( 'w2a-setting-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php
        }
     }

	public function w2a_setting_page_init() {
		register_setting(
			'w2a_setting_option_group', // option_group
			'w2a_setting_option_name', // option_name
			array( $this, 'w2a_setting_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'w2a_setting_setting_section', // id
			'Settings', // title
			array( $this, 'w2a_setting_section_info' ), // callback
			'w2a-setting-admin' // page
		);

		add_settings_field(
			'server_id_0', // id
			'server id', // title
			array( $this, 'server_id_0_callback' ), // callback
			'w2a-setting-admin', // page
			'w2a_setting_setting_section' // section
		);

		add_settings_field(
			'package_name_1', // id
			'package name', // title
			array( $this, 'package_name_1_callback' ), // callback
			'w2a-setting-admin', // page
			'w2a_setting_setting_section' // section
		);
	}

	public function w2a_setting_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['server_id_0'] ) ) {
			$sanitary_values['server_id_0'] = esc_textarea( $input['server_id_0'] );
		}

		if ( isset( $input['package_name_1'] ) ) {
			$sanitary_values['package_name_1'] = sanitize_text_field( $input['package_name_1'] );
		}

		return $sanitary_values;
	}

	public function w2a_setting_section_info() {
		
	}

	public function server_id_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="w2a_setting_option_name[server_id_0]" id="server_id_0">%s</textarea>',
			isset( $this->w2a_setting_options['server_id_0'] ) ? esc_attr( $this->w2a_setting_options['server_id_0']) : ''
		);
	}

	public function package_name_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="w2a_setting_option_name[package_name_1]" id="package_name_1" value="%s">',
			isset( $this->w2a_setting_options['package_name_1'] ) ? esc_attr( $this->w2a_setting_options['package_name_1']) : ''
		);
	}

}
if ( is_admin() ){
	$w2a_setting = new WASetting();

    /* 
 * Retrieve this value with:
 * $w2a_setting_options = get_option( 'w2a_setting_option_name' ); // Array of All Options
 * $server_id_0 = $w2a_setting_options['server_id_0']; // server id
 * $package_name_1 = $w2a_setting_options['package_name_1']; // package name
 */


if (isset($_GET['firebase']) && $_GET['firebase']=="send") {
    $title = $_GET['title'];
    $message = $_GET['body'];
    $id = $_GET['id'];
    $imageLink = $_GET['imageLink'];
    $selfUrl = $_GET['selfUrl'];

    $topic = $_GET['topic'];


    $fields = array(
        'to'  => '/topics/'.$topic,
        'priority' => 'high',
        'notification' => array(
            'body' => $message,
            'title' => $title,
            'sound' => 'default',
            'icon' => '',
            'image' => $imageLink
        ),
        'data' => array(
            'message' => $imageLink,
            'title' => $title,
            'sound' => 'default',
            'postID' => $id,
            'selfUrl' => $selfUrl,
            'imageLink' => $imageLink
        )


    );

   

    function sendPushNotification($fields = array())
    {
        $w2a_setting_options = get_option( 'w2a_setting_option_name' );
        // aikhane server key ta bosaben
        $API_ACCESS_KEY =$w2a_setting_options['server_id_0'];
        $headers = array(
        'Authorization: key=' . $API_ACCESS_KEY,
        'Content-Type: application/json'
    );
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
        $result = curl_exec($ch);
        curl_close($ch);

        if (isset($_SERVER['HTTP_REFERER']) && $_SERVER['HTTP_REFERER']!="") {
            $redirectUrl = $_SERVER['HTTP_REFERER'].'&response='.urlencode($result);
            header("Location:  $redirectUrl");
            die();
        }else{
            echo $result;
            die();
        }
       
    }

    sendPushNotification($fields);
}

}


