<?php

/**
 * Plugin Name: W2A by Sourov
 */



function filter_rest_allow_anonymous_comments()
{
    return true;
}
add_filter('rest_allow_anonymous_comments', 'filter_rest_allow_anonymous_comments');





add_filter('rest_prepare_post', 'my_filter_post', 10, 3);
function my_filter_post($data, $post, $context)
{


    // Does this have categories?
    if (!empty($data->data['categories'])) {
        $first = true;
        // Loop through them all
        foreach ($data->data['categories'] as $category_id) {
            // Get the actual Category Object
            if ($first) {
                $category = get_category($category_id);

                $data->data['w2a_by_sourov']["catName"] = $category->name;
            }
            $first = false;
        }
    }
    if (!empty($data->data['featured_media'])) {
        $image_full =  wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'full');
        $image_thumbnail =  wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'thumbnail');
        if ($image_full!=null) {
            $data->data['w2a_by_sourov']['image_full'] =$image_full[0];
        }
        if ($image_thumbnail!=null) {
            $data->data['w2a_by_sourov']['image_thumbnail'] =$image_thumbnail[0];
        }
    }

    return $data;
}



function search_google($actions, $page_object)
{
    $actions['google_link'] = '<a href="' .menu_page_url('w2a-settings', false).
'&type=post'.
'&postid='. urlencode($page_object->ID).
'&firebase=view'.
 '" class="google_link">' . __('Send notification') . '</a>';

    return $actions;
}

add_filter('post_row_actions', 'search_google', 10, 2);







 /**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class WASettings
{
    private $w2a_settings_options;

    public function __construct()
    {
        add_action('admin_menu', array( $this, 'w2a_settings_add_plugin_page' ));
        add_action('admin_init', array( $this, 'w2a_settings_page_init' ));
    }

    public function w2a_settings_add_plugin_page()
    {
        add_menu_page(
            'W2A Settings', // page_title
            'W2A Settings', // menu_title
            'manage_options', // capability
            'w2a-settings', // menu_slug
            array( $this, 'w2a_settings_create_admin_page' ), // function
            'dashicons-admin-tools', // icon_url
            2 // position
        );
    }

    public function w2a_settings_create_admin_page()
    {
        $this->w2a_settings_options = get_option('w2a_settings_option_name');
        
        if (isset($_GET['firebase']) && $_GET['firebase']=="view" && isset($_GET['postid'])) {
            $post =get_post($_GET['postid'])
       
       ?>

<div class="wrap">
    <h2>W2A Settings</h2>
    <p>W2A by Sourov settings page</p>
    <?php settings_errors();
    
            wp_enqueue_style('tableCss', plugin_dir_url(__FILE__) . '/inc/css/table.css', array(), '1.1', 'all');
            
            $w2a_settings_options = get_option('w2a_settings_option_name'); 
            
            if (isset($_GET['response'])) {
                $response = urldecode( $_GET['response']);
             echo'  <div class="notice notice-success is-dismissible hide" id="notificationFormNotice">
             <p>'. $response.'</p>
         </div>';
            }
            ?>

   
    <div class="section-form">
        <form method="get" action="">
            <div class="intro">
                <h1>Ready to send notification?</h1>
                <h2>Modify or just click "Send"</h2>
            </div>
            <label>Notification Title</label>
            <input type="text" name="title" value="<?php echo $post->post_title ; ?>" required>
            <label>Notification Body</label>
            <input type="text" name="body" value="<?php echo $post->post_title ; ?>" required>
            <label>Post ID</label>
            <input type="text" name="id" value="<?php echo $post->ID ; ?>" required>
            <label>Post URL</label>
            <input type="text" name="selfUrl" value="<?php echo get_permalink($post->ID) ; ?>" required>
            <label>Notification Image Link</label>
            <input type="text" name="imageLink"
                value="<?php echo wp_get_attachment_url(get_post_thumbnail_id($post->ID), 'thumbnail') ; ?>">
            <label>Notification Topic</label>
            <input type="text" name="topic" value="<?php echo $w2a_settings_options['app_package_name_1'] ; ?>" required>
            <input type="hidden" name="page" value="w2a-settings">
            <input type="hidden" name="firebase" value="send">
            <input type="submit" value="Send" />
        </form>
    </div>

</div>
<?php
        }
        if (isset($_GET['firebase']) && $_GET['firebase']=="send" && isset($_GET['tittle']) && isset($_GET['image']) && isset($_GET['postid'])) {
            include 'notification.php';
            $response = HTTPRequester::HTTPPost("http://localhost/service/foobar.php", array("postParam" => "foobar"));
        } elseif (!isset($_GET['firebase'])) {
            ?>

<div class="wrap">
    <h2>W2A Settings</h2>
    <p>W2A by Sourov settings page</p>
    <?php settings_errors(); ?>

    <form method="post" action="options.php">
        <?php
                    settings_fields('w2a_settings_option_group');
            do_settings_sections('w2a-settings-admin');
            submit_button(); ?>
    </form>
</div>
<?php
        }
    }

    public function w2a_settings_page_init()
    {
        register_setting(
            'w2a_settings_option_group', // option_group
            'w2a_settings_option_name', // option_name
            array( $this, 'w2a_settings_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'w2a_settings_setting_section', // id
            'Settings', // title
            array( $this, 'w2a_settings_section_info' ), // callback
            'w2a-settings-admin' // page
        );

        add_settings_field(
            'server_id_0', // id
            'server id', // title
            array( $this, 'server_id_0_callback' ), // callback
            'w2a-settings-admin', // page
            'w2a_settings_setting_section' // section
        );

        add_settings_field(
            'app_package_name_1', // id
            'app package name', // title
            array( $this, 'app_package_name_1_callback' ), // callback
            'w2a-settings-admin', // page
            'w2a_settings_setting_section' // section
        );
    }

    public function w2a_settings_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['server_id_0'])) {
            $sanitary_values['server_id_0'] = esc_textarea($input['server_id_0']);
        }

        if (isset($input['app_package_name_1'])) {
            $sanitary_values['app_package_name_1'] = sanitize_text_field($input['app_package_name_1']);
        }

        return $sanitary_values;
    }

    public function w2a_settings_section_info()
    {
    }

    public function server_id_0_callback()
    {
        printf(
            '<textarea class="large-text" rows="5" name="w2a_settings_option_name[server_id_0]" id="server_id_0">%s</textarea>',
            isset($this->w2a_settings_options['server_id_0']) ? esc_attr($this->w2a_settings_options['server_id_0']) : ''
        );
    }

    public function app_package_name_1_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="w2a_settings_option_name[app_package_name_1]" id="app_package_name_1" value="%s">',
            isset($this->w2a_settings_options['app_package_name_1']) ? esc_attr($this->w2a_settings_options['app_package_name_1']) : ''
        );
    }
}
if (is_admin()) {
    $w2a_settings = new WASettings();

    if (isset($_GET['firebase']) && $_GET['firebase']=="send") {
        $title = $_GET['title'];
        $message = $_GET['body'];
        $id = $_GET['id'];
        $imageLink = $_GET['imageLink'];
        $selfUrl = $_GET['selfUrl'];
    
        $topic = $_GET['topic'];
    
    
        $fields = array(
            'to'  => '/topics/'.$topic,
            'priority' => 'high',
            'notification' => array(
                'body' => $message,
                'title' => $title,
                'sound' => 'default',
                'icon' => '',
                'image' => $imageLink
            ),
            'data' => array(
                'message' => $imageLink,
                'title' => $title,
                'sound' => 'default',
                'postID' => $id,
                'selfUrl' => $selfUrl,
                'imageLink' => $imageLink
            )
    
    
        );

       

        function sendPushNotification($fields = array())
        {
            $w2a_settings_options = get_option('w2a_settings_option_name');
            // aikhane server key ta bosaben
            $API_ACCESS_KEY =$w2a_settings_options['server_id_0'];
            $headers = array(
            'Authorization: key=' . $API_ACCESS_KEY,
            'Content-Type: application/json'
        );
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
            $result = curl_exec($ch);
            curl_close($ch);

            if (isset($_SERVER['HTTP_REFERER']) && $_SERVER['HTTP_REFERER']!="") {
                $redirectUrl = $_SERVER['HTTP_REFERER'].'&response='.urlencode($result);
                header("Location:  $redirectUrl");
                die();
            }else{
                echo $result;
                die();
            }
           
        }

        sendPushNotification($fields);
    }
}


/*
 * Retrieve this value with:
 * $w2a_settings_options = get_option( 'w2a_settings_option_name' ); // Array of All Options
 * $server_id_0 = $w2a_settings_options['server_id_0']; // server id
 * $app_package_name_1 = $w2a_settings_options['app_package_name_1']; // app package name
 */
